### ISSUE TITLE
首页翻页会被转义

### ISSUE THREAD

**Issue by denity** [theme-materialized/hexo-theme-materialized#3]
在使用过程中，忽然碰到了地下换页的地方被转义直接输出
![11](https://user-images.githubusercontent.com/2181344/68746796-4c83e600-0634-11ea-889f-970bd8315499.png)

调试后，在文件
layout/_partial/archive.ejs 46行
增加一个转义参数 escape: false 解决。

**Comment by code004Accepted** [comment]
建议您提交一个PR，方便您成为Contributor

Bug已被核实，感谢您的贡献
