### ISSUE TITLE
请教一下 页面跳转和搜索框问题

### ISSUE THREAD

**Issue by TowerLi** [theme-materialized/hexo-theme-materialized#8]
1,页面跳转会加上 博客本身的地址,比如想转到weibo.com，会被重定向至blog.com/weibo.com，请问要怎么解决呢？
2.搜索框怎么才能实现搜索功能？

**Comment by code004Accepted** [comment]
1. 请在链接前加上`http://`或`https://`，例如`https://weibo.com`，这样链接就会被重定向至`weibo.com`了
2. 搜索框是自带的，您可以参见这里的[demo](https://theme-materialized.github.io/)，点击右上角的放大镜按钮后会弹出搜索框，搜索结果会随框中的输入而动态变化。搜索功能依赖`search.xml`（一个博客索引，会在`hexo g`时在本地生成），所以当文章很多或很长的时候，`search.xml`文件会很大，加载就会很慢

下图是demo中的搜索功能截图。这边连GitHub比较慢，所以`search.xml`没加载出来：![image.png](https://i.loli.net/2020/08/04/k8KFHzWGlgB7DVq.png)

---

UPDATE：下图是加载完毕后的状态：
![Screenshot 2020-08-04 234053.png](https://i.loli.net/2020/08/04/qRTeMGIPFkhur2J.png)

PS：如果您博客的访客主要来自国内，建议您使用Gitee/Coding而不是GitHub部署，否则像上面的`search.xml`和一些UI的图标都会很慢

**Comment by TowerLi** [comment]
感谢，解决了域名问题，搜索框问题可能真的是太卡了，search.xml加载不出来吧。

**Comment by code004Accepted** [comment]
> 感谢，解决了域名问题，搜索框问题可能真的是太卡了，search.xml加载不出来吧。

嗯，如果换到国内线路部署可能会快一些。感谢您提的Issue。
